# Text-specific configurations
text_model:
  preprocess_params:
    return_lst: false
  model_path: "data/processed/text/final_model"
  encoder_path: "data/processed/text/mpnet_encoder"
  label_encoder_path: "data/processed/text/label_encoder.pkl"
  class_weights: {0:1, 1:2.5, 2:1, 3:1}